# GHW workflow to build metislinux iso 
name: build metis iso per release
on:
  push:

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: artixlinux/runit:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Add user 'pwnwriter' with sudo privileges
        run: |
          sudo useradd -m -G sudo pwnwriter
          echo 'pwnwriter ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/pwnwriter
          sudo chmod 0440 /etc/sudoers.d/pwnwriter

      - name: Building packages
        run: |
          sudo -u pwnwriter bash -c '
          cp .makepkg_config/makepkg.conf /etc/makepkg.conf -r
          cat /etc/makepkg.conf
          bash build_pkgs.sh andromeda
          '

      - name: Uploading image to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./andromeda/pkgs-andromeda
          asset_name: metis-andromeda 
          tag: repo testing
          overwrite: true 
          body: Automated build, metis repo

