# GHW workflow to build metislinux iso 
name: build metis iso per release
on:
  push:

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: artixlinux/runit:latest

    steps:
      - uses: actions/checkout@v3
      - name: setup env
        run: |
          pacman -Syu binutils fakeroot sudo zip --noconfirm --needed 
          mkdir /home/build
          chgrp nobody /home/build
          chmod g+ws /home/build
          setfacl -m u::rwx,g::rwx /home/build
          setfacl -d --set u::rwx,g::rwx,o::- /home/build

      - name: Building packages
        run: |
          cp .makepkg_config/makepkg.conf /etc/makepkg.conf -r
          sudo -u nobody
          bash build_pkgs.sh andromeda 
          zip -r andromeda.zip andromeda/pkgs-andromeda/*' 

      - name: Uploading image to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./andromeda/pkgs-andromeda
          asset_name: metis-andromeda 
          tag: repo testing
          overwrite: true 
          body: Automated build, metis repo

